#!/bin/bash

STATE=$1
OPTION=$2
TABLET=$3

print_usage() {
    echo "Usage: hdmi <STATE> [option]"
    echo ""
    echo "  State : on/off"
	echo "	--tablet Indicate that the device is an Android tablet (default is false)"
    echo "  Available options:"
    echo "      --left-of"
    echo "      --right-of"
    echo "      --above"
    echo "      --below"
    echo "      --same-as (default)"
}

check_args() {
    if [[ $STATE != "on" ]] && [[ $STATE != "off" ]]; then
        print_usage
        exit
    elif [[ $OPTION != "--left-of" ]] && [[ $OPTION != "--right-of" ]] && [[ $OPTION != "--above" ]] && [[ $OPTION != "--below" ]] && [[ $OPTION != "--same-as" ]] && [[ -n $OPTION ]]; then
        print_usage
        exit
    fi
}

activate() {
    # The following command assumes that HDMI-1 exists, but depending on the computer,
    # it might not be true.
    # TODO : Make the script more generalized (I think that xrandr will mark the screen 
    # as connected)
    if [[ -z $OPTION ]]; then
        xrandr --output HDMI-1 --mode 1920x1080 --same-as eDP-1
    else
        xrandr --output HDMI-1 --mode 1920x1080 $OPTION eDP-1
    fi
}

activate_tablet() {
	ADB_OUTPUT=$(adb reverse tcp:3131 tcp:3131 2>&1)
	if [[ $ADB_OUTPUT == *"no devices/emulators found"* ]]; then
		echo "ERROR: No Android device connected. Remove this check if you want to continue over wifi"
		exit
	fi
	
	xrandr --addmode HDMI-1 1920x1080
    if [[ -z $OPTION ]]; then
        xrandr --output HDMI-1 --mode 1920x1080 --same-as eDP-1
    else
        xrandr --output HDMI-1 --mode 1920x1080 $OPTION eDP-1
    fi

	deskreen 2>/dev/null 1>/dev/null &
	echo -n "PASTE URI HERE: "
	read URI
	URI_LOCALHOST=$(echo $URI | sed 's/http:\/\/.*:3131/http:\/\/localhost:3131/g')
	echo "[+] Using $URI_LOCALHOST"
	adb shell am start -a android.intent.action.VIEW -d $URI_LOCALHOST 2>/dev/null 1>/dev/null &
}

deactivate() { 
    xrandr --output HDMI-1 --off
	killall deskreen
}

main() {
    check_args

    if [[ $STATE == "on" ]] && [[ -z $TABLET ]]; then
        activate
    	sleep 1
		i3-msg restart
	elif [[ $STATE == "on" ]] && [[ $TABLET == "--tablet" ]]; then
        activate_tablet
    	sleep 1
		i3-msg restart
    elif [[ $STATE == "off" ]]; then
        deactivate
    fi
}

main
